name: conquant_agro
description: Sistema de Gerenciamento de Fazendas
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  get: ^4.6.6
  
  # HTTP & Storage
  dio: ^5.4.0
  shared_preferences: ^2.2.2

  # Local Database
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  
  # Bluetooth
  flutter_blue_plus: ^1.30.0
  
  # Charts & Graphs
  fl_chart: ^0.65.0
  
  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # File Handling
  file_picker: ^10.3.3
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Utils
  intl: ^0.20.2
  dropdown_search: ^5.0.6
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  drift_dev: ^2.14.1

flutter:
  uses-material-design: true

  assets: